version: "3.7"

networks:
  reverse-proxy:
    external: true
    name: reverse-proxy
  internal:
    driver: bridge

services:
  php:
    build: .docker/app
    volumes:
      - ./:/app
    working_dir: /app
    env_file:
      - .env
    networks:
      - internal
  nginx:
    image: nginx:alpine
    volumes:
      - .docker/nginx/config/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./:/app
    ports:
      - 80:80
    networks:
      - reverse-proxy
      - internal